default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: goals_app_development

test:
  <<: *default
  database: goals_app_test
